### ISSUE TITLE
Не проще было сделать src.toLowerCase().contains(target.toLowerCase())?

### ISSUE THREAD

**Issue by coursar** [ryabinskiyna/avito#3]
https://github.com/ryabinskiyna/avito/blob/9f519e3ffb78c89a9f3514281a31f53d3351d559/src/main/java/ru/itpark/util/StringService.java#L7-L27

**Comment by coursar** [comment]
Ну и туда логику с нулевой длиной добавить

**Comment by ryabinskiyna** [comment]
@coursar согласен, проще.
В тоже время, я опирался на ответ человека под ником icza на это вопрос https://stackoverflow.com/a/25379180
в котором он провел анализ и показал, что использование lowercase для решение данной задачи раза в четыре медленнее. Поэтому я решил использовать regionMatches.
Что скажете?

**Comment by coursar** [comment]
Скажу, что преждевременная оптимизация - корень всех зол.

**Comment by ryabinskiyna** [comment]
@coursar "...Нам следует забывать о небольшой эффективности, например, в 97% случаев: преждевременная оптимизация - корень всех зол. Хотя мы не должны отказываться от своих возможностей в этих критических 3%..." :)
Если по существу, то я гуглил, как сделать поиск по части строки игнорируя регистр, наткнулся на этот метод и стало интересно, захотелось попробовать. В тоже время, я не до конца понимаю, как он работает. Например, зачем нужно это:
   final char firstLo = Character.toLowerCase(what.charAt(0)); 
   final char firstUp = Character.toUpperCase(what.charAt(0));
и затем сравнение. Зачем этот, как отмечает автор, "quick check"?
А на счет оптимизации, действительно есть какие-то минусы, подводные камни? Если есть, пожалуйста, объясните

**Comment by coursar** [comment]
Не нужно оптимизировать то, где пока "не тормозит". Т.к. чаще всего будет тормозить не там, а вы тратите время на то, что можно было сделать в одну строку )).

Тут логика достаточно хитрая - он и сравнивает первые буквы, чтобы не сравнивать всё, если не совпадают, то в исходной строке двигается на следующий символ.
